language: cpp
sudo: required
services: docker


before_install:
  - git clone https://github.com/smealum/ctrulib

install:
  - docker pull devkitpro/devkitarm
  - docker run -e ENABLE_COMPATIBILITY_REPORTING -v $TRAVIS_BUILD_DIR/ctrulib:/libctru devkitpro/devkitarm /bin/bash -ex /libctru/.travis/docker.sh

script:
  - docker run -e ENABLE_COMPATIBILITY_REPORTING -v $TRAVIS_BUILD_DIR:/3dsutils devkitpro/devkitarm /bin/bash -ex /3dsutils/docker.sh
